"""
OpenAI function tools for PuppyGraph Cypher queries.

- generate_cypher: Agent generates a Cypher query and returns it.
- execute_cypher: Executes a Cypher query against PuppyGraph via the PuppyGraph client.
"""

import json
import os

from puppygraph import PuppyGraphClient, PuppyGraphHostConfig

from agent_utils import get_system_prompt


def generate_cypher(cypher_query: str) -> str:
    """
    Return the PuppyGraph Cypher query generated by the agent.

    Args:
        cypher_query: The Cypher query string.

    Returns:
        The Cypher query string.
    """
    return cypher_query


def build_tool_spec() -> dict:
    """Build the tool spec with the system prompt baked into the description."""
    system_prompt = get_system_prompt()
    return {
        "type": "function",
        "function": {
            "name": "generate_cypher",
            "description": (
                "Return a PuppyGraph Cypher query for a graph question. "
                "Pass the complete Cypher query as cypher_query.\n\n"
                f"{system_prompt}"
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "cypher_query": {
                        "type": "string",
                        "description": "The PuppyGraph Cypher query string (e.g., 'MATCH (t:table) RETURN id(t) LIMIT 10')",
                    },
                },
                "required": ["cypher_query"],
            },
        },
    }


GENERATE_CYPHER_TOOL_SPEC = build_tool_spec()


# --- Execute Cypher tool puppygraph ---

def execute_cypher(cypher_query: str) -> str:
    """
    Execute a Cypher query against PuppyGraph and return the results as JSON.

    Args:
        cypher_query: The Cypher query string to execute.

    Returns:
        JSON string of the query results.
    """
    host = os.getenv("PUPPYGRAPH_HOST", "localhost")
    client = PuppyGraphClient(PuppyGraphHostConfig(host))
    try:
        res = client.cypher_query(cypher_query)
        print(res)
        return json.dumps(res, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


EXECUTE_CYPHER_TOOL_SPEC = {
    "type": "function",
    "function": {
        "name": "execute_cypher",
        "description": (
            "Execute a PuppyGraph Cypher query and return the results. "
            "Pass the complete Cypher query as cypher_query."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "cypher_query": {
                    "type": "string",
                    "description": "The PuppyGraph Cypher query string to execute (e.g., 'MATCH (t:table) RETURN id(t) LIMIT 10')",
                },
            },
            "required": ["cypher_query"],
        },
    },
}
