"""
OpenAI function tool for returning PuppyGraph Cypher queries.

The agent generates the Cypher (it has the schema in its system prompt).
This tool simply receives and returns the query.
"""

import json

from agent_utils import get_system_prompt


def generate_cypher(cypher_query: str) -> str:
    """
    Return the PuppyGraph Cypher query generated by the agent.

    Args:
        cypher_query: The Cypher query string.

    Returns:
        The Cypher query string.
    """
    return cypher_query


def build_tool_spec() -> dict:
    """Build the tool spec with the system prompt baked into the description."""
    system_prompt = get_system_prompt()
    return {
        "type": "function",
        "function": {
            "name": "generate_cypher",
            "description": (
                "Return a PuppyGraph Cypher query for a graph question. "
                "Pass the complete Cypher query as cypher_query.\n\n"
                f"{system_prompt}"
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "cypher_query": {
                        "type": "string",
                        "description": "The PuppyGraph Cypher query string (e.g., 'MATCH (t:table) RETURN id(t) LIMIT 10')",
                    },
                },
                "required": ["cypher_query"],
            },
        },
    }


GENERATE_CYPHER_TOOL_SPEC = build_tool_spec()


# --- Execute Cypher tool ---

def make_execute_cypher(client):
    """
    Create an execute_cypher function with the PuppyGraph client bound.

    Args:
        client: A PuppyGraphClient instance (from simple_client.py).

    Returns:
        A function(cypher_query: str) -> str that executes the query via Bolt.
    """
    from neo4j import GraphDatabase

    bolt_uri = f"bolt://{client.host}:7687"
    driver = GraphDatabase.driver(
        bolt_uri,
        auth=(client.username, client.password),
    )

    def execute_cypher(cypher_query: str) -> str:
        """Execute a Cypher query against PuppyGraph and return results."""
        try:
            with driver.session() as session:
                result = session.run(cypher_query)
                records = [dict(record) for record in result]
            return json.dumps(records, indent=2, default=str)
        except Exception as e:
            return f"Error executing query: {e}"

    return execute_cypher


EXECUTE_CYPHER_TOOL_SPEC = {
    "type": "function",
    "function": {
        "name": "execute_cypher",
        "description": (
            "Execute a PuppyGraph Cypher query and return the results. "
            "Only pass valid Cypher queries."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "cypher_query": {
                    "type": "string",
                    "description": "The Cypher query to execute (e.g., 'MATCH (t:table) RETURN id(t) LIMIT 10')",
                },
            },
            "required": ["cypher_query"],
        },
    },
}
