"""
OpenAI function tools for PuppyGraph Gremlin queries.

- generate_gremlin: Agent generates a Gremlin query and returns it.
- execute_gremlin: Executes a Gremlin query against PuppyGraph via the PuppyGraph client.
"""

import json
import os

from puppygraph import PuppyGraphClient, PuppyGraphHostConfig

from agent_utils import get_system_prompt


def generate_gremlin(gremlin_query: str) -> str:
    """
    Return the PuppyGraph Gremlin query generated by the agent.

    Args:
        gremlin_query: The Gremlin query string.

    Returns:
        The Gremlin query string.
    """
    return gremlin_query


def build_tool_spec() -> dict:
    """Build the tool spec with the system prompt baked into the description."""
    system_prompt = get_system_prompt()
    return {
        "type": "function",
        "function": {
            "name": "generate_gremlin",
            "description": (
                "Return a PuppyGraph Gremlin traversal for a graph question. "
                "Pass the complete Gremlin query as gremlin_query.\n\n"
                f"{system_prompt}"
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "gremlin_query": {
                        "type": "string",
                        "description": "The PuppyGraph Gremlin query string (e.g., \"g.V().hasLabel('table').id().limit(10)\")",
                    },
                },
                "required": ["gremlin_query"],
            },
        },
    }


GENERATE_GREMLIN_TOOL_SPEC = build_tool_spec()


# --- Execute Gremlin tool puppygraph ---

def execute_gremlin(gremlin_query: str) -> str:
    """
    Execute a Gremlin query against PuppyGraph and return the results as JSON.

    Args:
        gremlin_query: The Gremlin query string to execute.

    Returns:
        JSON string of the query results.
    """
    host = os.getenv("PUPPYGRAPH_HOST", "localhost")
    client = PuppyGraphClient(PuppyGraphHostConfig(host))
    try:
        res = client.gremlin_query(gremlin_query)
        return json.dumps(res, default=str)
    except Exception as e:
        return json.dumps({"error": str(e)})


EXECUTE_GREMLIN_TOOL_SPEC = {
    "type": "function",
    "function": {
        "name": "execute_gremlin",
        "description": (
            "Execute a PuppyGraph Gremlin query and return the results. "
            "Pass the complete Gremlin query as gremlin_query."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "gremlin_query": {
                    "type": "string",
                    "description": "The PuppyGraph Gremlin query string to execute (e.g., \"g.V().hasLabel('table').id().limit(10)\")",
                },
            },
            "required": ["gremlin_query"],
        },
    },
}
